services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: learn-english-bot
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ".postgres-data:/var/lib/postgresql/data:delegated"