"""Add in_progress field

Revision ID: 8b26c075a088
Revises: 901a8fc8cfb8
Create Date: 2022-05-02 11:35:06.872019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b26c075a088'
down_revision = '901a8fc8cfb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userwords', sa.Column('in_progress', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userwords', 'in_progress')
    # ### end Alembic commands ###
