"""Added required tables

Revision ID: 8e3a692efa1f
Revises: 
Create Date: 2022-04-26 14:21:54.074688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3a692efa1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english', sa.String(), nullable=True),
    sa.Column('russian', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_english'), 'dictionary', ['english'], unique=False)
    op.create_index(op.f('ix_dictionary_id'), 'dictionary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dictionary_id'), table_name='dictionary')
    op.drop_index(op.f('ix_dictionary_english'), table_name='dictionary')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
