"""Add usage mode

Revision ID: d6ddf1b40bf2
Revises: e0be76076ca2
Create Date: 2022-05-01 11:40:53.422341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models.users import UsageMode


# revision identifiers, used by Alembic.
revision = 'd6ddf1b40bf2'
down_revision = 'e0be76076ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    usage_mode = postgresql.ENUM(UsageMode, name="usagemode")
    usage_mode.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('usage_mode', usage_mode, server_default='new_words', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usage_mode')
    usage_mode = postgresql.ENUM(UsageMode, name="usagemode")
    usage_mode.drop(op.get_bind())
    # ### end Alembic commands ###
